# Generated by Django 4.0.1 on 2022-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasket',
            name='shop_id',
            field=models.IntegerField(default=0, verbose_name='shop_id'),
        ),
    ]
