# Generated by Django 4.0.1 on 2022-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_userbasket_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasket',
            name='creation_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
