# Generated by Django 4.0.1 on 2022-02-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_full_sum_count'),
        ('app_shops', '0003_userbasket_creation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.profile', verbose_name='user'),
        ),
    ]
