# Generated by Django 4.0.1 on 2022-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0004_alter_userbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinshop',
            name='article',
            field=models.CharField(blank=True, default='NOTARTICLE', max_length=25, verbose_name='article'),
        ),
        migrations.AddField(
            model_name='productinshop',
            name='full_description',
            field=models.TextField(blank=True, default='NOTDESCRIPTION', max_length=1000, verbose_name='full_description'),
        ),
    ]
