# Generated by Django 4.0.1 on 2022-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0005_productinshop_article_productinshop_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergarbage',
            name='full_description',
            field=models.TextField(blank=True, default='NOTDESCRIPTION', max_length=1000, verbose_name='full_description'),
        ),
    ]
