# Generated by Django 4.0.1 on 2022-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0006_usergarbage_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasket',
            name='product_photo',
            field=models.CharField(blank=True, default='default.jpg', max_length=39, verbose_name='product_photo'),
        ),
    ]
