# Generated by Django 4.0.1 on 2022-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0007_userbasket_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='product_photo',
            field=models.CharField(blank=True, default='default.jpg', max_length=100, verbose_name='product_photo'),
        ),
    ]
