# Generated by Django 4.0.1 on 2022-01-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=39, verbose_name='city')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='street')),
                ('postcode', models.IntegerField(default=0, verbose_name='postcode')),
                ('house_number', models.IntegerField(default=0, verbose_name='house_number')),
                ('apartment_number', models.IntegerField(default=0, verbose_name='apartment_number')),
                ('data_of_birth', models.DateField(blank=True, null=True, verbose_name='data of birth')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('purchases_count', models.IntegerField(default=0, verbose_name='account amount')),
                ('photo', models.ImageField(default='default.jpg', upload_to='user_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'users profile',
            },
        ),
    ]
