# Generated by Django 4.0.1 on 2022-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_sum_count',
            field=models.IntegerField(default=0, verbose_name='account amount'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('a', 'beginner'), ('b', 'started'), ('c', 'regular'), ('d', 'constant')], default='a', max_length=1, verbose_name='status'),
        ),
    ]
