# Generated by Django 4.0.1 on 2022-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_profile_full_sum_count_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_sum_count',
            field=models.IntegerField(default=0, verbose_name='spent'),
        ),
    ]
